# Numpy is a python library used for working with arrays.


# Why use Numpy?

## 1.Numpy provieds efficient storage
## 2.It is fast and easy to learn
## 3.Numpy uses les memory to store data

### *Importing numpy

In [1]:
#importing numpy
import numpy as np

### *Creating numpy array

In [12]:
#Creating Numpy array

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))  #type(): This built-in Python function tells us the type of the object passed to it and it shows that arr is numpy.ndarray type.



[1 2 3 4 5]
<class 'numpy.ndarray'>


In [13]:
# Using tuple to create numpy array

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [14]:
#Dimensions in arrays



In [15]:
arr = np.array(42) # 0-D array

print(arr)

42


In [16]:
arr = np.array([1, 2, 3, 4, 5]) # 1=D array

print(arr)

[1 2 3 4 5]


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 2-D array

print(arr)

[[1 2 3]
 [4 5 6]]


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])  # 3-D array

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [22]:
#Checking the dimensions of the numpy arrays  :  ndim

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim,"-D")
print(b.ndim,"-D")
print(c.ndim,"-D")
print(d.ndim,"-D")

0 -D
1 -D
2 -D
3 -D


In [24]:
#Higher Dimensional Arrays
#An array can have any number of dimensions.
#When the array is created, we can define the number of dimensions by using the ndmin argument.

arr = np.array([1, 2, 3, 4], ndmin=3)

print(arr)
print('number of dimensions :', arr.ndim)

[[[1 2 3 4]]]
number of dimensions : 3


### * NumPy Array Indexing

In [26]:
#1-D array
#Get the first element from the following array:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [27]:
#Get the second element from the following array:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [28]:
#Get third and fourth elements from the following array and add them.

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [29]:
#2-D array
#Access the 2nd element on 1st dim:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [30]:
#Access the 5th element on 2nd dim:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])


print('5th element on 2nd dim: ', arr[1, 4])

5th element on 2nd dim:  10


In [31]:
#3-D array
#Access the third element of the second array of the first array:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [32]:
#Negative Indexing
#Use negative indexing to access an array from the end.

#Print the last element from the 2nd dim:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


### *Numpy array slicing


In [5]:
#Slicing in python means taking elements from one given index to another given index.

# pass slice instead of index like this: [start:end].

# Or define the step, like this: [start:end:step].

#If  don't pass start its considered 0

#If  don't pass end its considered length of array in that dimension

#If  don't pass step its considered 1

In [6]:
#Slice elements from index 1 to index 5 from the following array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [7]:
#Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [8]:
#Slice elements from the beginning to index 4 :

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [11]:
#Negative Slicing
#Use the minus operator to refer to an index from the end:

#Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [12]:
#STEP
#Use the step value to determine the step of the slicing:

#Return every other element from index 1 to index 5:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [19]:
#Return every other element from the entire array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [20]:
#Slicing 2-D Arrays
#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [25]:
#From both elements, return index 2:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [26]:
#From both elements, slice index 1 to index 4 , this will return a 2-D array:


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [29]:
#Checking the Data Type of an Array
#The NumPy array object has a property called dtype that returns the data type of the array:

#Get the data type of an array object:
arr = np.array([1, 2, 3, 4],np.int64)

print(arr.dtype)

int64


In [30]:
#Get the data type of an array containing strings:

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [31]:
#Create an array with data type string:

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [32]:
#Create an array with data type 4 bytes integer:

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [36]:
#Converting Data Type on Existing Arrays
#The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [37]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### * Copy and View

In [42]:
#COPY:Make a copy, change the original array, and display both arrays:
#VIEW:Make a view, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y=arr.view()
arr[0] = 42

print(arr)
print("copy=",x)
print("view",y)

[42  2  3  4  5]
copy= [1 2 3 4 5]
view [42  2  3  4  5]


### *NumPy Array Shape


In [43]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [44]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### *NumPy Array Reshaping

In [46]:
#Reshape From 1-D to 2-D: The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)  #(rows,colms)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [47]:
##Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [50]:
#Reshaping is view not copy
#base - returns the original object
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x=arr.reshape(2, 4)
print(x.base)

[1 2 3 4 5 6 7 8]


In [52]:
#Unknown Dimension:Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
#Pass -1 as the value, and NumPy will calculate this number

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
#Flattening the arrays:Flattening array means converting a multidimensional array into a 1D array.
#We can use reshape(-1) to do this.

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### *NumPy Array Iterating

In [2]:
#Iterate on the elements of the following 1-D array:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [3]:
#Iterate on the elements of the following 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [5]:
#Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6


In [6]:
#Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [8]:
#Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [10]:
#Iterating Arrays Using nditer()
#The function nditer() is a helping function that can be used from very basic to very advanced iterations.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [11]:
#Iterating With Different Step Size:Iterate through every scalar element of the 2D array skipping 1 element:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [12]:
#Iterating Array With Different Data Types:: use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
#NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

#Iterate through the array as a string:

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [16]:
#corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.
#1-D array
arr = np.array([1, 2, 3,4,5,6])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


In [17]:
#2-D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### *NumPy Joining Array

In [18]:
#Concatenating
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [22]:
#Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### *NumPy Splitting Array

In [23]:
#use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [25]:
#Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [27]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### *Searching Arrays

In [28]:
#To search an array, use the where() method.
#Find the indexes where the value is 4:

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [29]:
#searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
#Find the indexes where the value 7 should be inserted:

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [31]:
#By default the left most index is returned, but we can give side='right' to return the right most index instead.
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


### *Sorting Arrays

In [33]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [34]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [35]:
arr = np.array([True, False, True]) # Boolean array

print(np.sort(arr))

[False  True  True]


In [36]:
#Sort a 2-D array:

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


### * Filtering Arrays

In [37]:
#Getting some elements out of an existing array and creating a new array out of them is called filtering.
#If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


### *Generate Random Number


In [39]:
from numpy import random

x = random.randint(100)

print(x)

13


In [40]:
x=random.randint(100, size=(5))

print(x)

[94  7 98  2 81]


In [45]:
x=random.rand(2) #float 
print(x)

[0.14947725 0.86411747]


In [44]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

x = random.randint(100, size=(3, 5))

print(x)

[[96 42 72  8  7]
 [22 39 33 67 97]
 [23 79  9 86 20]]


In [46]:
x = random.rand(3, 5)

print(x)

[[0.11969264 0.70146764 0.91853955 0.62313226 0.46756738]
 [0.85293287 0.78689894 0.91191871 0.83756198 0.20947166]
 [0.24077296 0.65346362 0.56502565 0.65828307 0.14715313]]


In [48]:
#The choice() method allows you to generate a random value based on an array of values.
#The choice() method takes an array as a parameter and randomly returns one of the values

x = random.choice([3, 5, 7, 9])

print(x)

3


In [49]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 5 9 7 9]
 [5 5 5 5 9]
 [7 7 9 7 3]]
